include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
    - build/**
    - ios/**
    - android/**

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    non_constant_identifier_names: false
    depend_on_referenced_packages: false
    curly_braces_in_flow_control_structures: false
    use_build_context_synchronously: false
    no_leading_underscores_for_local_identifiers: false
